In [2]:
import torch
!pip install transformers
import transformers 
from transformers import TransfoXLTokenizer, TransfoXLModel, TransfoXLLMHeadModel,TransfoXLModel

# OPTIONAL: if you want to have more information on what's happening, activate the logger as follows
import logging
logging.basicConfig(level=logging.INFO)

# Load pre-trained model tokenizer (vocabulary from wikitext 103)
tokenizer = TransfoXLTokenizer.from_pretrained('transfo-xl-wt103')

# Tokenized input
text_1 = "Who was Jim Henson ?"
text_2 = "Jim Henson was a puppeteer"


tokenized_text_1 = tokenizer.tokenize(text_1)
tokenized_text_2 = tokenizer.tokenize(text_2)

# Convert token to vocabulary indices
indexed_tokens_1 = tokenizer.convert_tokens_to_ids(tokenized_text_1)
indexed_tokens_2 = tokenizer.convert_tokens_to_ids(tokenized_text_2)

# Convert inputs to PyTorch tensors
tokens_tensor_1 = torch.tensor([indexed_tokens_1])
tokens_tensor_2 = torch.tensor([indexed_tokens_2])

     |████████████████████████████████| 1.9MB 6.8MB/s 
     |████████████████████████████████| 3.2MB 51.6MB/s 
     |████████████████████████████████| 890kB 55.7MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp37-none-any.whl size=893262 sha256=9f0bf89aee0506a53ee4efa853c12150d1e24594a51f70d4605d641e4e5c0380
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


INFO:filelock:Lock 140378265706064 acquired on /root/.cache/huggingface/transformers/6860d92833eb9d2a42cf185e974ca967fbf4cd58fa8d3d9298e56b9ef7ff8d5c.56c8ef92e693414ef2313bde4ba3679a404de1edbcd5a5780def3971f9706850.lock


INFO:filelock:Lock 140378265706064 released on /root/.cache/huggingface/transformers/6860d92833eb9d2a42cf185e974ca967fbf4cd58fa8d3d9298e56b9ef7ff8d5c.56c8ef92e693414ef2313bde4ba3679a404de1edbcd5a5780def3971f9706850.lock


In [ ]:
pip install transformers

     |████████████████████████████████| 1.8MB 8.5MB/s 
     |████████████████████████████████| 890kB 32.1MB/s 
     |████████████████████████████████| 2.9MB 45.0MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893261 sha256=8414f2258c637e0889a6bc81c479240e29d36566bfafe8abc9da09edbc226cbd
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


Let's see how to use TransfoXLModel to get hidden states

In [ ]:
# Load pre-trained model (weights)
model = TransfoXLModel.from_pretrained('transfo-xl-wt103',torchscript=True)
model.eval()

# If you have a GPU, put everything on cuda
tokens_tensor_1 = tokens_tensor_1.to('cuda')
tokens_tensor_2 = tokens_tensor_2.to('cuda')
model.to('cuda')

with torch.no_grad():
    # Predict hidden states features for each layer
    hidden_states_1, mems_1 = model(tokens_tensor_1)
    # We can re-use the memory cells in a subsequent call to attend a longer context
    hidden_states_2, mems_2 = model(tokens_tensor_2, mems=mems_1)

INFO:filelock:Lock 140116865881928 acquired on /root/.cache/torch/transformers/439371439c726aeec36ef037c63b76ae3e384957090780502c2464ca82017ae1.27301fe0016a634426a4129084dcc45038bd1eb454d0b18accf84dcf4adc5563.lock


INFO:filelock:Lock 140116865881928 released on /root/.cache/torch/transformers/439371439c726aeec36ef037c63b76ae3e384957090780502c2464ca82017ae1.27301fe0016a634426a4129084dcc45038bd1eb454d0b18accf84dcf4adc5563.lock
/usr/local/lib/python3.6/dist-packages/transformers/configuration_transfo_xl.py:145: FutureWarning: The config parameter `tie_weight` is deprecated. Please use `tie_word_embeddings` instead.
  FutureWarning,
INFO:filelock:Lock 140116865881928 acquired on /root/.cache/torch/transformers/891af5f0c8372327a961a768d4ee40b7ca95c428f9384c534e73b9b655c75468.923bd8e0844a782c35f009eddd08a3600739804fbe13bd234f592f36230ab8a9.lock


INFO:filelock:Lock 140116865881928 released on /root/.cache/torch/transformers/891af5f0c8372327a961a768d4ee40b7ca95c428f9384c534e73b9b655c75468.923bd8e0844a782c35f009eddd08a3600739804fbe13bd234f592f36230ab8a9.lock


/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py:434: UserWarning: Setting attributes on ParameterList is not supported.
  warnings.warn("Setting attributes on ParameterList is not supported.")
/usr/local/lib/python3.6/dist-packages/transformers/modeling_transfo_xl.py:445: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  indices_i = mask_i.nonzero().squeeze()


And how to use TransfoXLLMHeadModel

In [ ]:
# Tokenized input
text_1 = "In the field of NLP, language modeling involves predicting the next word in a sentence."
text_2 = "Applying this model recursively, will yield a computer-generated text. "
tokenized_text_1 = tokenizer.tokenize(text_1)
tokenized_text_2 = tokenizer.tokenize(text_2)

# Convert token to vocabulary indices
indexed_tokens_1 = tokenizer.convert_tokens_to_ids(tokenized_text_1)
indexed_tokens_2 = tokenizer.convert_tokens_to_ids(tokenized_text_2)

# Convert inputs to PyTorch tensors
tokens_tensor_1 = torch.tensor([indexed_tokens_1])
tokens_tensor_2 = torch.tensor([indexed_tokens_2])

In [ ]:
# Load pre-trained model (weights)
model = TransfoXLLMHeadModel.from_pretrained('transfo-xl-wt103',torchscript=True)
model.eval()
 
# If you have a GPU, put everything on cuda
# tokens_tensor_1 = tokens_tensor_1.to('cuda')
# tokens_tensor_2 = tokens_tensor_2.to('cuda')
# model.to('cuda')
 
with torch.no_grad():
    # Predict all tokens
    predictions_1, mems_1 = model(tokens_tensor_1)
    # We can re-use the memory cells in a subsequent call to attend a longer context
    predictions_2, mems_2 = model(tokens_tensor_2, mems=mems_1)
 
# get the predicted last token
predicted_index = torch.argmax(predictions_2[0, -1, :]).item()
predicted_token = tokenizer.convert_ids_to_tokens([predicted_index])[0]
#assert predicted_token == 'who'
predicted_token

/usr/local/lib/python3.6/dist-packages/transformers/configuration_transfo_xl.py:145: FutureWarning: The config parameter `tie_weight` is deprecated. Please use `tie_word_embeddings` instead.
  FutureWarning,
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py:434: UserWarning: Setting attributes on ParameterList is not supported.
  warnings.warn("Setting attributes on ParameterList is not supported.")


'<eos>'

In [ ]:
predictions_2.shape, predictions_1.shape

(torch.Size([1, 13, 267735]), torch.Size([1, 17, 267735]))

In [ ]:
text_1, text_2

('In the field of NLP, language modeling involves predicting the next word in a sentence.',
 'Applying this model recursively, will yield a computer-generated text. ')

In [ ]:
for i in range(5):
    predicted_index = torch.argmax(predictions_2[0, i, :]).item()
    predicted_token = tokenizer.convert_ids_to_tokens([predicted_index])[0]
    print(predicted_token, end=' ')

the prediction to , the 

In [ ]:
mems_next = mems_2
tokens_tensor_next = tokens_tensor_2

for i in range(20):    
    with torch.no_grad():
        # We can re-use the memory cells in a subsequent call to attend a longer context
        predictions_next, mems_next = model(tokens_tensor_next, mems=mems_next)

    predicted_index_tensor = torch.argmax(predictions_next[0, -1, :])
    tokens_tensor_next = torch.cat(
        [tokens_tensor_2[:, 1:], predicted_index_tensor.reshape(1, 1)], 1)
        
    predicted_index = predicted_index_tensor.item()
    predicted_token = tokenizer.convert_ids_to_tokens([predicted_index])[0]
    print(predicted_token, end=' ')

<eos> <eos> <eos> This will be the computer @-@ based on a computer @-@ this model recursively , <eos> <eos> 

In [ ]:

tokenizer.convert_ids_to_tokens([predicted_index])

['<eos>']

In [ ]:
tokens_tensor_2.shape

torch.Size([1, 13])

In [ ]:
tokens_tensor_2, predicted_index

(tensor([[ 52842,     56,   1248, 126172,      2,    209,   8641,      8,   2147,
              12,   3247,   2043,      3]]), 0)

In [ ]:
predicted_index_tensor = torch.argmax(predictions_next[0, -1, :]).reshape(1, 1)
torch.cat([tokens_tensor_2[:, 1:], predicted_index_tensor], 1).shape

torch.Size([1, 13])

In [ ]:
torch.argmax(predictions_next[0, -1, :]).reshape(1, 1)

tensor([[0]])

In [ ]:
tokens_tensor_2.shape

torch.Size([1, 13])

In [ ]:
tokenizer = TransfoXLTokenizer.from_pretrained('transfo-xl-wt103',torchscript=True)
model = TransfoXLLMHeadModel.from_pretrained('transfo-xl-wt103',torchscript=True)

/usr/local/lib/python3.6/dist-packages/transformers/configuration_transfo_xl.py:145: FutureWarning: The config parameter `tie_weight` is deprecated. Please use `tie_word_embeddings` instead.
  FutureWarning,
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py:434: UserWarning: Setting attributes on ParameterList is not supported.
  warnings.warn("Setting attributes on ParameterList is not supported.")


In [ ]:
line = "This car was produced in China"
line_tokenized = tokenizer.tokenize(line)
line_indexed = tokenizer.convert_tokens_to_ids(line_tokenized)
tokens_tensor = torch.tensor([line_indexed])
#tokens_tensor = tokens_tensor.to(device)

In [ ]:
max_predictions = 50
mems = None
for i in range(max_predictions):
    predictions, mems = model(tokens_tensor, mems=mems)
    predicted_index_tensor = torch.topk(predictions[0, -1, :],5)[1][1] 
    predicted_index = predicted_index_tensor.item()
    predicted_token = tokenizer.convert_ids_to_tokens([predicted_index])[0]
    print(predicted_token)
    
    tokens_tensor = torch.cat((tokens_tensor, predicted_index_tensor.reshape(1, 1)), dim=1)

,
which
is
a
product
in
the
region
,
which
was
released
.
<eos>
The
other
cars
were
manufactured
by
China
.
<eos>
The
two
others
are
produced
by
the
United
Kingdom
.
The
other
cars
are
manufactured
in
the
UK
.
The
two
others
were
manufactured
in
the
United


In [ ]:
valu, idx = torch.topk(predictions[0, -1, :],5, sorted=True)
valu, idx

(tensor([-0.8353, -0.8776, -3.0536, -4.1320, -4.4769], grad_fn=<TopkBackward>),
 tensor([ 806,  119,  207,  159, 3566]))

In [ ]:
predictions.shape

torch.Size([1, 55, 267735])

In [ ]:
# Specify a path
PATH1 = "transfomer_xl.pt"

# Save
torch.save(model.state_dict(), PATH1)
